# Main menu buttons
CONTINUE_BUTTON = 'Continue'
NEW_GAME_BUTTON = 'New game'
CONTROLS_BUTTON = 'Controls'
SETTINGS_BUTTON = 'Settings'
QUIT_BUTTON = 'Quit'
MM_ESC = 'Esc - Main menu'
MM_RIGHT = 'Right - Movement to the right'
MM_LEFT = 'Left - Movement to the left'
MM_F5 = 'F5 - Quick saving'
MM_F9 = 'F9 - Quick loading'
MM_TAB = 'Tab - Inventory'
MM_X = 'X or Up - Engage/Enter'
MM_DOWN = 'Down - Sit down'
MM_SPACE = 'Space - Jump'
ED_MD = 'Go to Editor mode'
GO_TO_ED = 'EDITOR MODE'

INV_INSC = 'Inventory'
KEY_FOUND = 'Found'
KEY_NOT_FOUND = 'Not found'
