# Main menu buttons
CONTINUE_BUTTON = 'Продолжить'
NEW_GAME_BUTTON = 'Новая игра'
CONTROLS_BUTTON = 'Управление'
SETTINGS_BUTTON = 'Настройки'
QUIT_BUTTON = 'Выход'
MM_ESC = 'Esc - Главное меню'
MM_RIGHT = 'Вправо - Движение вправо'
MM_LEFT = 'Влево - Движение влево'
MM_F5 = 'F5 - Быстрое сохранение'
MM_F9 = 'F9 - Быстрая загрузка'
MM_TAB = 'Tab - Инвентарь'
MM_X = 'Ч или Вверх - Использовать/войти'
MM_DOWN = 'Вниз - Присесть'
MM_SPACE = 'Пробел - Прыжок'